### ISSUE TITLE
0.10.1 - Cannot mount USB Drive

### ISSUE THREAD

**Issue by enzotito** [XorTroll/Goldleaf#670]
Release 0.10.1 breaks mounting an external USB drive (1TB SanDisk SSD) which works under 0.10

Explore content | USB Drives | USB drive information | Found drive count: 0

Console : 16.0.2
Atmosphere : 1.5.2

**Comment by paoloalby** [comment]
Same problem for me. Witch 0.10 I can read my USB HardDisk connected directly to the Switch, as usually.

Now, with 0.10.1 it crashes every time. I have to use Quark, then it works.

But I prefer to use directly my USB Drive on USB-C port Switch.
Please fix it.

**Comment by hiberabyss** [comment]
Have same problem!

**Comment by mtscott42** [comment]
I am having the same issue.  Cannot mount the USB drive.  Love this tool and keep up the good work but can you please fix it?  :)

**Comment by theend92** [comment]
Same Issue. 0.9 and 0.10 ok but 0.10.1 didnt work. But i need it for Zelda.
Quark is working.

Console : 16.0.2
Atmosphere : 1.5.3

**Comment by karawsr** [comment]
Has anyone found a solution to this?? Still doesn't seem like you can access USB drives

**Comment by XorTroll** [comment]
I think I fixed this some commits ago, could somebody test with the last GitHub actions builds to see if it's indeed fixed?

**Comment by XorTroll** [comment]
This is unrelated to the issue, Quark != USB drives

**Comment by greg36pl** [comment]
Just tested build #169 from Actions and can confirm USB drive mounting and browsing once again works properly.
Thanks Xor!

**Comment by mtscott42** [comment]
What am I doing wrong, I still cant mount usb drive.  I have to use TinWoo to mount and really like this app.

**Comment by SkyLeite** [comment]
In v1 Goldleaf can mount the HDD, but clicking browse makes the application freeze then crash

**Comment by mtscott42** [comment]
Verified that newest release is working again.  Thank you!

**Comment by XorTroll** [comment]
Alright then

**Comment by mtscott42** [comment]
You rock! Thanks much for you hard work!
